### PR TITLE
Add Environments and Roles from file

### PR DESCRIPTION
**Pull request by drryu**
Adding RolesFilePath and EnvironmentsFilePath variables, so that we are able to dynamically get these values from the client.

Use Case: Need to dynamically assign roles and environments to the Octopus agent during orchestration of client machine. DSC does not allow dynamic assignment of variables at run time. With the introduction of these variable, we can write out the roles and environments to a file (eg: C:\Temp\Roles.txt) and then have the DSC resource read the roles from the file when installing the agent.

### CODE REVIEW

**Comment by matt-richardson** [comment]
I'm not convinced adding these parameters is the best direction to take. Also, out of curiousity, how are you writing the role/environment files? Wont you run into the same issue?

I think its probably better to follow the approach outlined in [how to separate configuration and environment data](https://msdn.microsoft.com/en-us/powershell/dsc/configdata).

Let me know if that works for you.

**Comment by drryu** [comment]
Hi @matt-richardson ,

I looked into the configuration data route, however the roles and environments can not be changed once the mof is generated (DSC does not support this).

When provisioning the servers, we ask the user for the roles and environments that they want to assign to the server. We take the parameters and write it to a file on the server that is provisioned. After that we run Start-DscConfiguration, which picks the roles and environments from the files that were created during provisioning. We don't run into the same issue, because the file contents are read at runtime, on the provisioned machine.

We need to be able to ask the user what roles and environments the machine needs to be in, during provisioning and there is no real way for us to set that once the MOF is generated. We **could** generate a new MOF every time a new machine is provisioned, but that breaks our process of using [partial configurations](https://msdn.microsoft.com/en-us/powershell/dsc/partialconfigs)

**Comment by matt-richardson** [comment]
Hi @drryu,

I understand your desire to have this functionality and appreciate your efforts to contribute back, but unfortunately it doesn't match with the direction we want to go.

If we added these properties, I can see a situation where someone wants to read the api key from a file, so there's another property, and then the server url, so there's another property, and so on.

I would suggest one of the following:

* Change the process to generate a per machine MOF file once the desired roles/environments are known
* Assign dummy roles/environments in the cOctopusTentacle resource, and then add a script resource after the cOctopusTentacle which uses the Octopus API to update to the correct roles / environments
* As its OSS, you could create your own fork of the project and use that

Sorry I cant give you better news than that.

Regards,
Matt

**Comment by drryu** [comment]
Hello @matt-richardson,

Thanks for the suggestions. I will see if we can incorporate one of the changes that you have suggested.

Thanks,

Rashief.

**Pull request closed without merging**
