### PR TITLE
Fixed issue where worker pool regisration failed

### PR DESCRIPTION
**Pull request by twerthi**
Fixed issue where worker pool registration would fail because roles and environments were not specified.

### CODE REVIEW

**Comment by stopthatastronaut** [comment]
I just tweaked the tests on a local clone of this branch and I'm running in vagrant now. If it's all happy I'll add a small commit and merge.

**Comment by stopthatastronaut** [comment]
OK, so I changed the tests on my local clone and it blew up with "Please specify an environment name, e.g., --environment=Development" (coming from tentacle.exe)

The intent is to be able to spin up a tentacle registered into a worker pool but without roles and environments, like the below snippet, right? 

```
cTentacleAgent WorkerTentacle
        {
            Ensure = "Present";
            State = "Started";
            Name = "WorkerTentacle";
            DisplayName = "My Worker Tentacle"

            # Registration - all parameters required
            ApiKey = $ApiKey;
            OctopusServerUrl = $OctopusServerUrl;
            # Optional settings
            ListenPort = 10937;
            DefaultApplicationDirectory = "C:\Applications"
            PublicHostNameConfiguration = "ComputerName"
            TentacleHomeDirectory = "C:\Octopus\WorkerTentacleHome"

            WorkerPools = @("Default Worker Pool")
        }
```
(example lifted from tentacle_scenario_01_install.ps1)

**Comment by twerthi** [comment]
Correct.  I tried this on my local instance and it registered fine.  I'll take another look, thanks for finding the bug :)

**Comment by twerthi** [comment]
Reproduced the problem you encountered.  The difference was in the cTentacleAgent definition, you specifically didn't list Environments or Roles where I had them, but they were empty.  I'll revisit how I'm checking to see if they're null or empty.

**Comment by twerthi** [comment]
Pushed a commit that should fix that issue.

**Comment by stopthatastronaut** [comment]
Ah! Makes sense. Back on this today

**Pull request merged**
