### PR TITLE
Added Policy parameter to cTentacleAgent module.

### PR DESCRIPTION
**Pull request by j0monty**
Policy parameter wasn't included as an option in cTentacle - added it to cTentacleAgent.psm1 and cTentacleAgent.schema.mof.

### CODE REVIEW

**Comment by matt-richardson** [comment]
Hi @j0monty 

Thanks for the contribution. Before we can accept it, can you please sign the CLA?

Before we merge, we'd like to have some tests added to make sure it functions (and continues to function) as desired.

At a high level, I think we'll need to:

* [ ] update [octopus-serverspec-extensions](https://github.com/OctopusDeploy/octopus-serverspec-extensions/blob/master/lib/octopus_serverspec_extensions/type/octopus_deploy_tentacle.rb) to add a new function for policy (it'd be very similar to the `has_tenant?` one)
* [ ] update [the setup script](https://github.com/OctopusDeploy/OctopusDSC/blob/master/Tests/configure-octopus-for-tentacle-tests.ps1) to ensure we have a policy available to test with 
* [ ] update [this DSC configuration](https://github.com/OctopusDeploy/OctopusDSC/blob/master/Tests/Tentacle_Scenario_01_Install.ps1) to specify the new policy on the Tentacle
* [ ] update [this test](https://github.com/OctopusDeploy/OctopusDSC/blob/master/Tests/Spec/tentacle_scenario_01_install_spec.rb) to check that its worked correctly

If you could add that, that would be awesome. If you cant, we will look to do that at some point, but not sure exactly when.

Thanks again!

**Comment by j0monty** [comment]
Thanks @matt-richardson  - I've made the changes as suggested. Let me know if you need anything else.

Thanks!

**Comment by j0monty** [comment]
Also, I signed the CLA but it won't update...

**Comment by matt-richardson** [comment]
You. Are. Awesome.

I'll look into the CLA issue and get back to you.

**Comment by PaulStovell** [comment]
@j0monty thanks for the contribution! Not sure what's going on with CLA Assistant but I can see you signed it, so green light to go ahead anyway. Over to @matt-richardson

**Comment by matt-richardson** [comment]
Thanks @j0monty, thats now been released as version `2.0.79`.

**Pull request merged**
