### PR TITLE
Octopus deploy master

### PR DESCRIPTION
**Pull request by twerthi**

### CODE REVIEW

**Comment by twerthi** [comment]
Closing, I have my repo all messed up.

**Comment by twerthi** [comment]
Contributor Sesna is me, it must have changed the username when I committed to my repo from my home computer.

**Comment by stopthatastronaut** [comment]
Hi Twerthi

I pulled the fork down and ran tests - there's a few failing. We've also got a merge conflict, so those couple of things will need resolving before we can merge the changes in.

To run tests yourself, you need Pester v4, PSScriptAnalyzer and vagrant, along with either Hyper-V or VirtualBox installed locally, or an AWS/Azure account. There's a section in the [readme](https://github.com/OctopusDeploy/OctopusDSC#development) that should help get you started, but feel free to hit me up if you need assistance.

J

**Comment by twerthi** [comment]
I've tried several times to resolve the conflict, but I'm afraid my GitHub experience is a hindering factor.  I'm sure this is an elementary question, but the conflict seems to revolve around the script analyzer issues you fixed post-merge from my last PR, how do I get those changes into mine? 

PS - My experience is almost 100% Microsoft TFSVC, so Git is a little foreign to me.

**Comment by stopthatastronaut** [comment]
Hey, you can sync your fork from our upstream by following [these instructions](https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser).

quite often, a sync in that direction will get you past merge conflicts, though you may have to resolve one or two minor bits in your editor. Good luck!

**Comment by twerthi** [comment]
I tried that a few times already, but that was before I realized I had multiple branches.  I'll try it again now that I've merged and consolidated into one.

**Comment by twerthi** [comment]
Okay, I've tried again and am having similar results.  This is most likely due to inexperience with GitHub, gut I cannot for the life of me figure out how to get this to merge.  In TFS, when resolving merge conflicts I can chose which sections from which file to keep, is there a way to do that in GitHub?

**Comment by stopthatastronaut** [comment]
Yup, the [web-based merge tool](https://github.com/OctopusDeploy/OctopusDSC/pull/171/conflicts) lets you view the merge conflict and you can opt to keep one side or the other. In this case it looks like a very tiny conflict - whitespace on the end of L773. You should be able to open the file in a text editor locally, resolve that by keeping the version from `OctopusDeploy-master` and the conflict will be gone.

It's pretty easy if you're using, say, VS Code with the git extensions - the tool gives you a little button allowing you to choose which side of the merge you want to keep.

**Comment by twerthi** [comment]
OMFG thank you!  I looked at that web interface on and off for days trying to figure that out, the VS Code suggestion worked perfectly.  That was extremely frustrating, and made me feel like a complete idiot!  Okay, now that the merge conflict is resolved, I'll see about getting the tests worked out.

**Comment by twerthi** [comment]
@stopthatastronaut, I had a failed example through Vagrant 
Failed examples:

rspec ./Spec/tentacle_scenario_01_install_spec.rb:191 # Windows DSC should have applied dsc configuration successfully

##teamcity[blockClosed name='Testing Scenario tentacle_scenario_01_install']

The failure was due to $OctopusServerUrl being an empty string in Test-TargetResource, is that a valid scenario?

**Comment by matt-richardson** [comment]
Glad to hear you’re making progress, @twerthi. 

There are a few example configs in tentacle scenario 1 - some have `RegisterWithServer` set to `$false` - in that case, the server url is not required. 

Did you note which one of the resource blocks failed?

**Comment by twerthi** [comment]
@matt-Richardson, thank you for that information.  I will code for that condition and try again.

**Comment by twerthi** [comment]
This should fix it, the tests worked on my end.

**Comment by twerthi** [comment]
Question, which I think I know the answer to, a tentacle can be installed as a worker without being a deployable target, correct?

**Comment by twerthi** [comment]
@MichaelJCompton thanks for getting back to me!  I reviewed what I've added, that scenario is supported.

**Comment by twerthi** [comment]
Is there anything you're waiting on me to do?

**Comment by stopthatastronaut** [comment]
Back on deck and running tests now...

**Comment by twerthi** [comment]
Were they successful?

**Comment by twerthi** [comment]
Hello :)  Just curious how things were coming along?

**Comment by stopthatastronaut** [comment]
Hey Twerthi, sorry for that massive delay. 

I finally bit the bullet and esablished a parallel build plan on our internal TeamCity server, which is much better than the ramshackle solution I had before.

Currently one failing Pester test

```
[11:24:46][Pester tests]       [+] Returns True when Ensure is set to Absent and Tentacle does not exist 163ms
[11:24:46][Pester tests] Push-Location : Cannot find path '/Octopus Deploy/Tentacle' because it does not exist.
[11:24:46][Pester tests] At /opt/TeamCity/BuildAgent/work/f3f3624609f2f06d/OctopusDSC/DSCResources/cTentacleAgent/cTentacleAgent.psm1:125 char:5
[11:24:46][Pester tests] +     Push-Location "${env:ProgramFiles}\Octopus Deploy\Tentacle"
[11:24:46][Pester tests] +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[11:24:46][Pester tests] + CategoryInfo          : ObjectNotFound: (/Octopus Deploy/Tentacle:String) [Push-Location], ItemNotFoundException
[11:24:46][Pester tests] + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.PushLocationCommand
```

Looks like it's not defending against the "set to absent/not installed" condition. Shouldn't be a big change. 

Thanks for hanging in there with this PR. We're chatting about some better processes around our open source stuff, so in future we can make this whole thing smoother.

**Comment by twerthi** [comment]
@stopthatastronaut, I reviewed the code and am confused in how that test is failing.  The function failing is the Get-TentacleThumbprint which has only two references, both of which are in the Test-TargetResource function.  However, both references are only called when Ensure is set to Present according to if ($Ensure -eq "Present" -and ![string]::IsNullOrEmpty($OctopusServerUrl)) condition.  Would you mind pointing me in the right direction?  I have to be missing something :)

**Comment by stopthatastronaut** [comment]
I'll pull this latest version down and have a look today

**Comment by twerthi** [comment]
Thank you, I appreciate it.

**Comment by stopthatastronaut** [comment]
On my local machine, which has a tentacle installed, I get a different error, and a passing test

`Instance Tentacle1 of Tentacle has not been configured on this machine. Available instances: Tentacle.`

I usually have a couple of tentacles installed, naturally, but not by that name. Obviously our CI agents don't have tentacles on them (they run under Linux with Powershell core). 

So, looks like it's the test _after_ the error that's the issue, which is `It 'Returns True when Ensure is set to Present and Tentacle exists'`. I reckon it might be because your two mocks are defined within the `It {}` block, rather than just before it, and/or because `Get-TentacleFingerprint` isn't mocked - because the call within `Test-TargetResource` is trying to contact the real tentacle.exe (which fails).

**Comment by twerthi** [comment]
Ah!  Yes, Get-TentacleFingerprint returns the calls the tentacle.exe which returns that exact message when the instance doesn't exist.  Thanks!  That gives me what I needed :)

**Comment by twerthi** [comment]
@stopthatastronaut I am following the directions to run vagrant to run the tests before I submit the commit, however I cannot seem to get it to run.  Vagrant keeps saying, "The machine with the name 'provider' was not found configured for this Vagrant environment." when running vagrant up -- provider hyperv  Am I doing something wrong?

**Comment by stopthatastronaut** [comment]
Looks like you've got a space where you shouldn't have one

`vagrant up -- provider hyperv``
should be
`vagrant up --provider hyperv`

`build-hyper-v.ps1` ought to do the job too. Though I haven't used that in a while, as I have the luxury of using the our AWS account with `build-aws.ps1`

**Comment by twerthi** [comment]
LOL!  I'd deleted that comment because I was unintelligent and didn't read the part where you run the build-hyper-v.ps1.  The pester tests are all working, vagrant is having some issues, but I think its operator error.  I've submitted the commit, though.

**Comment by stopthatastronaut** [comment]
Cool. I'll check how things look in Team City

**Comment by stopthatastronaut** [comment]
Still the same test popping the error maybe randomise the tentacle name here so your local tentacle doesn't mask the problem?

https://github.com/OctopusDeploy/OctopusDSC/blob/abf264ab8489fee4e39a59ac81d93635cb387855/OctopusDSC/Tests/cTentacleAgent.Tests.ps1#L109

**Comment by twerthi** [comment]
Is it a pester test that is failing?

**Comment by twerthi** [comment]
At one point I had a tentacle called tentacle1 installed, but had since removed it.  It would appear that it still returns when calling the tentacle.exe.  I am now able to reproduce the issue and will attempt to fix it.

**Comment by stopthatastronaut** [comment]
Yep, a pester test. If you can try it in a fresh VM, you'll probably see it. I think.

**Comment by twerthi** [comment]
Okay, give that a go.  All pester tests working, but I'm having a difficult time getting vagrant past the setting of SMB shares.  It keeps failing, the cmdkey command shows an IP address that isn't what the host or the VM have, so I'm not sure what's going on here.  cmdkey /add:192.168.1.3 ... but that IP isn't on the subnet the host and VM are on.

**Comment by twerthi** [comment]
Did this last version work better?

**Comment by twerthi** [comment]
Greetings!  I got latest today so that I was up do date.  All Pester and Vagrant tests came back successful.

**Comment by stopthatastronaut** [comment]
Hey twerthi! Awesome news. There's been a good chunk of changes made in master recently, so that's excellent.

We just hit end-of-business here, I'll catch up with Matt in the morning and we'll see what we can do about merging.

**Comment by twerthi** [comment]
Looks like I may have jumped the gun, I think I see 2 failed pester tests.  I'll look into it.

**Comment by twerthi** [comment]
Hmm, just re-ran the pester tests only and all 675 succeeded.  Re-running entire test package.

**Comment by twerthi** [comment]
I didn't realize the vagrant.log file was appended to, not overwritten so what I thought was a failure was from an old run.  I re-ran all pester and vagrant tests, everything came back with 0 failures.

**Comment by stopthatastronaut** [comment]
Hey @Twerthi ! Apologies for taking so long, but this is now (finally) merged!

Thanks for contributing to OctopusDSC!

Jason

**Comment by stopthatastronaut** [comment]
btw: we're going to do a couple of tweaks before publishing that version, so there may be a short delay before it pops up on the gallery.

Cheers

J

**Comment by twerthi** [comment]
Absolutely!  I've an interview with Octo Wednesday, fingers crossed!

**Pull request merged**
