### PR TITLE
Use nullable bool for forcessl

### PR DESCRIPTION
**Pull request by matt-richardson**
Use a nullable bool for `ForceSSL`, to allow for "use whatever the current settings is.
Requested in https://github.com/OctopusDeploy/OctopusDSC/pull/263#issuecomment-742459392

### CODE REVIEW

**Comment by BenAkor** [comment]
@matt-richardson This looks great. Just what we need to maintain our desired state. Thank you very much for the work on it. When we change ForceSSL to $null we will be able to maintain our desire state on every chef run and not have the Octopus DSC and our code fighting against each other on every chef client run. This is good so far. Looking forward to testing it.

**Comment by aae42** [comment]
@matt-richardson @BenAkor nice work!

i think i would prefer the default config to be `$null`, to signify that the desired state on the forcessl is "disabled" to be handled outside of the resource, (like how `$AutoLoginEnabled` is used)  but could see how that could be considered a breaking change... 

in the absence of being able to handle the whole SSL certificate situation inside the DSC resource (which is probably out of scope, honestly), it's good to be able to disable the enforcement of forcessl to allow for us to configure this elsewhere

**Comment by matt-richardson** [comment]
Here's a package containing these changes. You can install it from a [local PSRepository](https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-local-psrepositories?view=powershell-7.1) to test it out.

I'm hoping to push this out soon, but I'm just being cautious - I don't really want to break peoples stuff a few days before Christmas :)

[OctopusDSC.4.0.957.nupkg.zip](https://github.com/OctopusDeploy/OctopusDSC/files/5726677/OctopusDSC.4.0.957.nupkg.zip)

**Comment by matt-richardson** [comment]
@BenAkor, @aae42 - have either of you been able to test this? I'd like to get it merged soon.

**Comment by aae42** [comment]
> @BenAkor, @aae42 - have either of you been able to test this? I'd like to get it merged soon.

having difficulty testing this with Chef, so, a nullable bool would work great if the default was set to null instead of false, with Chef we're not able to pass a null bool, we can only do true or false bools:

https://docs.chef.io/resources/dsc_resource/#properties

still looking for a solution

**Comment by matt-richardson** [comment]
> > @BenAkor, @aae42 - have either of you been able to test this? I'd like to get it merged soon.
> 
> @matt-richardson having difficulty testing this with Chef, so, a nullable bool would work great if the default was set to null instead of false, with Chef we're not able to pass a null bool, we can only do true or false bools:
> 
> https://docs.chef.io/resources/dsc_resource/#properties
> 
> still looking for a solution

Ahh, that's a pain. Unfortunately, changing the default could be considered a breaking change. (I'm second guessing myself on this right now, so I may come to a different conclusion later.)

Looks like @twerthi is getting close with his PR #267 that adds a new resource to setup the ssl cert. Will that help?

**Comment by matt-richardson** [comment]
Closing as stale.

**Pull request closed without merging**
