### PR TITLE
Added support for custom tentacle comms port

### PR DESCRIPTION
**Pull request by PashCracken**
To support the case where we have a Octopus tentacle in Azure behind a loadbalancer, we need to be able to specify the tentacle comms port option from tentacle.exe. This way the Octopus server can call the listening tentacle on one port and the LB/NAT forwards the request to the ListenPort on the VM in Azure

### CODE REVIEW

**Comment by PashCracken** [comment]
The CLA is actually signed

**Comment by alfhenrik** [comment]
> The CLA is actually signed

That'll be because of a mismatch between the user details in the commit ( @SaaSOps ) and PR ( @PashCracken ).

Cheers,
Henrik

**Comment by SaaSOps** [comment]
I accidentally logged in as the SaasOps user when committing the code.  @SaaSOps and @PashCracken is actually the same person :-) How do I fix this?

**Comment by matt-richardson** [comment]
No worries, @PashCracken - all good now on the CLA side of things. Thanks for the contribution - really appreciate it.

Before we merge, it'll need a few more changes. If you're up for doing them, that'd be great, otherwise we'll get to them as soon as we can.

* [ ] [README-cTentacleAgent.md](https://github.com/OctopusDeploy/OctopusDSC/blob/master/README-cTentacleAgent.md) will need updating to mention the new parameter
* [ ] likewise, so will [OctopusDSC/Examples/cTentacleAgent_ListeningTentacle.psm1](https://github.com/OctopusDeploy/OctopusDSC/blob/master/OctopusDSC/Examples/cTentacleAgent_ListeningTentacle.psm1)
* [ ] if possible, it'd be good to have something in [OctopusDSC/Tests/cTentacleAgent.Tests.ps1](https://github.com/OctopusDeploy/OctopusDSC/blob/master/OctopusDSC/Tests/cTentacleAgent.Tests.ps1), but i'm aware that's not always easy - its not the most testable of code
* [ ] one of the [E2E test scenarios](https://github.com/OctopusDeploy/OctopusDSC/tree/master/Tests/Scenarios) will need to be updated to use this new parameter, and the [related test spec](https://github.com/OctopusDeploy/OctopusDSC/tree/master/Tests/Spec) will need to be updated as well.

Also, just to make sure I understand, should the [firewall port that gets opened](https://github.com/PashCracken/OctopusDSC/blob/7ce9d8d87d2c84d0cd143b43dc843f79de48cea8/OctopusDSC/DSCResources/cTentacleAgent/cTentacleAgent.psm1#L496) be the `$tentacleCommsPort` in this scenario, or does it stay as is?

**Comment by PashCracken** [comment]
Hi,

The firewall should stay as it is. The VM where the Tentacle is installed listens to the ListenPort as normal and really does not know anything about the LoadBalancer and NAT rules needed to reach this VM and Port. 
Seen externally from the Octopus server all the VM's have the same public ip address, but have different ports. So this external port is what is needed for registration with the server and this is what this pull request solves.

It's a bit difficult to test this. I'm able to add a test scenario and a test spac, but I can't seem to find a supported way to verify the configuration. The tentacle will be offline seen from the Octopus server since there is no loadbalancer/NAT in this setup. So the only thing that makes sense to verify is that the registration port is set correctly and that don't seem to be supported by the rspec tests. If it's possible it would be good if you could show me how.

I'll look into the other changes you suggest, but testing seems difficult

/Jan

**Comment by matt-richardson** [comment]
Sorry for the delay, @PashCracken - been super busy at OctopusHQ.
Looking at this now.

**Comment by matt-richardson** [comment]
This is now available in `2.0.181`

**Pull request merged**
